### ISSUE TITLE
Mention the enhanced PG Adapter in the README?

### ISSUE THREAD

**Issue by searls** [rails/solid_cable#34]
Congratulations on the merge into Rails as a default!

Writing to ask if you'd be open to linking to the [actioncable-enhanced-postgresql-adapter](https://github.com/reclaim-the-stack/actioncable-enhanced-postgresql-adapter) gem in your notice about postgres in the README, as it supports messages >8KB relatively seamlessly.

**Comment by searls** [comment]
Tagging @jpcamara since I just noticed that this commit https://github.com/rails/solid_cable/commit/ba1b1e54755249a028de69918db5071f02772688 is only 2 hours old

**Comment by jon-sully** [comment]
@searls [actioncable-enhanced-postgresql-adapter](https://github.com/reclaim-the-stack/actioncable-enhanced-postgresql-adapter) is essentially an alternative option to `solid_cable`, right? They both essentially serve the same purpose?

**Comment by searls** [comment]
This gem is substsantially different from Solid Cable, as it benefits from PG's LISTEN/NOTIFY for push (as opposed to polling), but includes a solution for the 8KB limit by storing the data as transient records.

Yes, it is an alternative to using solid_cable, but since the README already has a notice that PG's LISTEN/NOTIFY is supported by the postgres adapter (with that 8KB caveat), it seems like it'd be most helpful to readers to also learn about this third party option.

**Comment by jon-sully** [comment]
Makes sense! Just trying to keep track of the layers they each serve 👍 thanks

**Comment by npezza93** [comment]
Howdy @searls! Appreciate the suggestion but i think for now im going to lean towards no. Looks like there is an open pr to enhance the pg adapter in rails with these changes and based on the comments in https://github.com/rails/rails/pull/49634, https://github.com/rails/rails/pull/49897 core seems frosty to the idea of suggesting the gem. Id like to wait to see how that pr shakes out before i add the note.
